### ISSUE TITLE
Blathers should be a little bit quieter

### ISSUE THREAD

**Issue by jordanlewis** [otan-cockroach/blathers-bot#2]
In the case where you've already contributed to CockroachDB, and your PR has no problems, I think Blathers should probably not say anything.

Also, the update messages can be a little bit too noisy. I don't think it's necessary for blathers to comment when you re-push. Check out https://github.com/cockroachdb/cockroach/pull/47586 for an example of what I mean.

**Comment by andreimatei** [comment]
^- LOL

**Comment by otan** [comment]
^_^

**Comment by otan** [comment]
You can turn this off actually: https://github.com/otan-cockroach/blathers-bot/blob/master/github_webhook.go#L478 

Just omit that line.

**Comment by otan** [comment]
resolved by https://github.com/otan-cockroach/blathers-bot/commit/fab289dfb6005ae69945cc04718fb2df6719d5fb
